### ISSUE TITLE
mmls unable to parse coreos GPT

### ISSUE THREAD

**Issue by joachimmetz** [sleuthkit/sleuthkit#1444]
mmls unable to parse coreos GPT

Test data:

`curl -LO https://stable.release.core-os.net/amd64-usr/current/coreos_production_vmware_ova.ova`
`tar xfv coreos_production_vmware_ova.ova`

```
gdisk -l fuse/vmdk1
GPT fdisk (gdisk) version 1.0.4

Disk device is fuse/vmdk1
Partition table scan:
  MBR: hybrid
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with hybrid MBR; using GPT.
Disk fuse/vmdk1: 17805312 sectors, 8.5 GiB
Sector size (logical): 512 bytes
Disk identifier (GUID): 00000000-0000-0000-0000-000000000001
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 34, last usable sector is 17805278
Partitions will be aligned on 2048-sector boundaries
Total free space is 8125 sectors (4.0 MiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            4096          266239   128.0 MiB   EF00  EFI-SYSTEM
   2          266240          270335   2.0 MiB     EF02  BIOS-BOOT
   3          270336         2367487   1024.0 MiB  FFFF  USR-A
   4         2367488         4464639   1024.0 MiB  FFFF  USR-B
   6         4464640         4726783   128.0 MiB   8300  OEM
   7         4726784         4857855   64.0 MiB    FFFF  OEM-CONFIG
   9         4857856        17801215   6.2 GiB     FFFF  ROOT
```

```
mmls fuse/vmdk1 
DOS Partition Table
Offset Sector: 0
Units are in 512-byte sectors

      Slot      Start        End          Length       Description
000:  Meta      0000000000   0000000000   0000000001   Primary Table (#0)
001:  -------   0000000000   0000000000   0000000001   Unallocated
002:  000:001   0000000001   0000004095   0000004095   GPT Safety Partition (0xee)
003:  000:000   0000004096   0000266239   0000262144   Win95 FAT32 (0x0c)
004:  -------   0000266240   0017805311   0017539072   Unallocated
```

**Comment by joachimmetz** [comment]
there is no way to tell in the mmls output that this is a MBR/GPT hybrid, in contrast to gdisk

also why does mmls default to MBR? but is does not do so for other GPT images e.g. those with a protective MBR. What is the expected behavior here?

**Comment by joachimmetz** [comment]
This behavior also seems to affect libtsk/pytsk

```
source_analyzer.py coreos_production_vmware_ova_image.vmdk
Source type		: storage media image

OS: location: coreos_production_vmware_ova_image.vmdk
  VMDK: 
    TSK_PARTITION: location: /
      TSK_PARTITION: 0, start offset: 0 (0x00000000)
      TSK_PARTITION: 1, start offset: 0 (0x00000000)
      TSK_PARTITION: 2, start offset: 512 (0x00000200), location: /p1
      TSK_PARTITION: 3, start offset: 2097152 (0x00200000), location: /p2
        TSK: location: /
      TSK_PARTITION: 4, start offset: 136314880 (0x08200000)

Completed.
```

This behavior does not appear to mentioned in http://www.sleuthkit.org/sleuthkit/docs/api-docs/4.5/vspage.html

Side note: this docpage is also hard to read without line wrapping in the text blocks.
