### ISSUE TITLE
Windows compilation warnings due to duplicated strnlen

### ISSUE THREAD

**Issue by miguel-negrao** [sleuthkit/sleuthkit#3196]
**Describe the bug or problem**

When compiling **libtsk** with **msbuild** I get a warning about `strnlen`

```
2>D:\a\keyword_search\keyword_search\sleuthkit\tsk\base\tsk_base_i.h(208,52): warning C4273: 'strnlen': inconsistent dll linkage [D:\a\keyword_search\keyword_search\sleuthkit\win32\libtsk\libtsk.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\string.h(351,25): message : see previous definition of 'strnlen' [D:\a\keyword_search\keyword_search\sleuthkit\win32\libtsk\libtsk.vcxproj]
```

Is appears the **HAVE_STRNLEN** is not set ?

**To Reproduce**
MSBuild.exe tsk-win.sln /p:configuration=Release /p:platform=x64 /t:libtsk /m

The version of SleuthKit you are using:
 484a7e8ee3812debf31c2166a509e47d9f197ef5 sleuthkit (sleuthkit-4.12.1-1591-g484a7e8ee)

Where you got it from: 
git submodule

**Operating Environment (please complete the following information):**
 - OS: github runner windows-latest
     - ImageOS=win22
     - ImageVersion=20250209.1.0
 - Version: MSBuild version 17.12.12+1cce77968 for .NET Framework
 - Compiler: `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\CL.exe`

**Comment by simsong** [comment]
Neat. Can you post the log file or the GitHub Action?

**Comment by miguel-negrao** [comment]
relevant part of the github action below and relevant log part attached.

[0_build (x64)-tsk.txt](https://github.com/user-attachments/files/18884844/0_build.x64.-tsk.txt)

```YAML
name: keyword_search builds on Windows

on:
  push:
    branches:
      - '**' # This will trigger the action for all branches
  pull_request:
    branches:  # Specify the branches for which pull_request events should trigger the action
      - main
      - develop

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x64]
    runs-on: windows-latest

    env:
      TSK_HOME: "${{ github.workspace }}/sleuthkit/"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
      - uses: microsoft/setup-msbuild@v2

      - name: Install nuget and ant
        run: |
          choco install nuget.commandline
          choco install ant --ignore-dependencies

      - name: bash printenv
        shell: bash
        run: |
          printenv | sort

      - name: Cache nuget packages
        uses: actions/cache@v4
        id: nuget-cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget

      - name: Cache TSK build
        id: tsk-cache
        uses: actions/cache@v4
        with:
          path: |
            sleuthkit/win32/**/Release_NoLibs
            sleuthkit/win32/**/x64
            sleuthkit/win32/Release_NoLibs
            sleuthkit/win32/x64/Release
          key: ${{ runner.os }}-tsk-${{ matrix.targetplatform }}-${{ hashFiles('sleuthkit/**/*.cpp', 'sleuthkit/**/*.h', 'sleuthkit/win32/**/*') }}
          restore-keys: |
            ${{ runner.os }}-tsk-${{ matrix.targetplatform }}-

      - name: restore TSK nuget packages
        run: nuget restore sleuthkit/win32/tsk-win.sln

      # windows already has strnlen, have to define HAVE_STRNLEN to stop defining another version of that function.
      # /p:DefineConstants="HAVE_STRNLEN" doesn't seem to solve it
      - name: Build libtsk
        run: MSBuild.exe tsk-win.sln /p:configuration=Release /p:platform=x64 /t:libtsk /m
        working-directory: sleuthkit/win32
```

Btw, I can't get the cache to work with msbuild... if you have any tips, they are welcome. In any case building just libtsk is 1m30s so not a problem.
Btw2, wouldn't it be easier to maintain a common approach with cmake + vcpkg for win, linux, osx assuming all dependencies are in vcpkg ? I believe the following should work on all osses (I tested on windows only).


```
      - uses: friendlyanon/setup-vcpkg@v1
        with:
          committish: 1d0f0a396cf00af25fbcb5550917c25ac64aa240
          save-always: true

      - name: Configure CMake
        shell: bash
        run: >
          cmake -B build -S .
          -D "CMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release
``` 

 It would also be nice to have libtsk on vcpkg, would make it much easier to use in other software. I do apreciate these things take time to setup, so it might a be a nice long term goal.
